### ISSUE TITLE
Mutations on the user object's custom_attributes is not working

### ISSUE THREAD

**Issue by Boburmirzo** [authgear/authgear_deno_hook#8]
Hi, 

Mutations on the user object's custom_attributes are not working. While I was able to mutate standard_attribute. According to the docs:

https://docs.authgear.com/integrate/events-hooks#mutations-on-the-user-object

Here are easy steps on how to reproduce this issue:

1. Start by logging into your [[Authgear dashboard](https://portal.authgear.com/)](https://portal.authgear.com/). 
2. Navigate to your Authgear Dashboard's **Advanced**->**Hooks** section.
3. **Add** a new **Blocking Event**.
4. Choose the Block Hook **Type** as the *TypeSctipt* and set the Event option to *User* *pre-create*. You will write a new Typescript function from scratch.
5. Click on **Edit Script** under the **Config** option.
6. Write a function logic for how you integrate any external or internal API into the editor. For example:

`import { EventUserPreCreate, HookResponse } from "https://deno.land/x/authgear_deno_hook@v1.1.0/mod.ts";

export default async function(e: EventUserPreCreate): Promise<HookResponse> {
    return {
       is_allowed: true,
    mutations:{
      user: {
          custom_attributes: {"Newattribute": "fsdfdsfdsf", "test": "fsfdsfsd"},
          standard_attributes: {"name": "John"}
      }
    },
  };
}`

7. Save changes.
8. Try to create a new user from Admin Portal.
9. You will see that standard_attributes is updated while a custom attribute is not added/updated:

![image](https://github.com/authgear/authgear_deno_hook/assets/14247607/d7b982e8-7cf8-424e-b5d3-03fa09651769)

**Expected output:**

I should see the existing _Newattribute_ value set to _fsdfdsfdsf_ and a new attribute _test_ has been added with its value.

**Comment by fungc-io** [comment]
@Boburmirzo the custom attribute should be snake case in lowercase alphabet, 
can you try `newattribute` instead of `Newattribute`?
if that's confusing perhaps we should show `newattribute` in the portal.

New attributes cannot be added by user mutation, it must be first added in the Portal>User Profile > Custom Attributes page

**Comment by Boburmirzo** [comment]
@fungc-io Yes, that makes sense. Let me try it so.

**Comment by Boburmirzo** [comment]
Great, I confirm that it is working:) Thanks!

![image](https://github.com/authgear/authgear_deno_hook/assets/14247607/09fe2ad6-5856-49f1-8351-643b0835d50f)

**Comment by fungc-io** [comment]
created follow up issue in https://github.com/authgear/authgear-server/issues/3251
